json.id airport.id
json.name airport.name
json.size airport.size
json.iata airport.iata
json.icao airport.icao
json.city airport.city
json.state airport.state
json.country airport.country
json.latitude airport.latitude
json.longitude airport.longitude